apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc
  labels:
    app: coordinates_api
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    name: web
  clusterIP: None
  selector:
    app: coordinates_api